### ISSUE TITLE
Truncate not applied correctly in PreallocatedFile::close

### ISSUE THREAD

**Issue by LeonardoDaga** [tni/teensy-samples#4]
Thank you tni for the really interesting software.
I've found (I think) a small bug in the closure of the pre-allocated file.
I've verified this error because I've modified the source code to allow a continuous fast multi-file logging (with 8mb file size) to operate on acquisitions bigger than 2Gb (I've a 64Gb SD card) and the end of a closed file didn't match with the start of a new opened file. 
The amount missed was just 512 bytes, the size of a sector.

The bug is in the instruction of the _PreallocatedFile::close()_ function.
`if(next_sector) file.truncate((next_sector - first_sector - 1) * 512 + partial_sector_len);`

that should be:
`if(next_sector) file.truncate((next_sector - first_sector) * 512 + partial_sector_len);`
 
In my opinion, you shouldn't remove 1 from the difference _next_sector - first_sector_.
This amount is already  the number of the sector of the file minus 1, because _next_sector_ is still the last sector of the file and not the _first_sector_ of the following file.

**Comment by tni** [comment]
Your are correct. I actually fixed this, but forgot to upload the fix.
